---
title: "paper2"
description: |
  Reproducing graphs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggplot2)
```

## read in data and clean the names
```{r}
trust <- read_csv(here("research_data", "trust.csv")) %>%
  clean_names()
```
## show names
```{r}
names(trust)
```
## convert response values to percentages (as per Table 3)
```{r}
trust %>%
  tabyl(experiment, response) %>%
  adorn_percentages()
```
## mutate dataset to add new variable "agegroup" with two possible values representing the two age groups
```{r}
trust <- trust %>%
  mutate(agegroup = case_when(age_group_participants == 0 ~ "3-5 year olds", 
                              age_group_participants == 1 ~ "5-6 year olds"))
```

## creating the graph using ggplot
```{r}
trust %>%
  gather("condition_information", "response",-agegroup) %>%
  ggplot(aes(agegroup, response, fill = condition_information)) +
  geom_bar(position = "dodge", stat = "identity") +
  theme_bw()
```
