---
title: "Week 3"
description: |
 reproducibility project planning
author:
  - name: Bonnie Butler
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Paper 1

Hill, S. E., Prokosch, M. L., DelPriore, D. J., Griskevicius, V., & Kramer, A. (2016). Low childhood socioeconomic status promotes eating in the absence of energy need. *Psychological Science, 27*, 354-364. https://doi.org/10.1177/0956797615621901

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797615621901)
- [OSF](https://osf.io/x8q4j)

## Paper 2

Plebanek, D. J., & Sloutsky, V. M. (2017). Costs of selective attention: When children notice what adults miss. *Psychological Science, 28(6)*, 723-732. https://doi.org/10.1177/0956797617693005

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797617693005)
- [OSF](https://dx.doi.org/10.7910/DVN/7TA47E)

## Paper 3

Putnam, A. L., Ross, M. Q., Soter, L. K., & Roediger III, H. L. (2018). Collective narcissism: Americans exaggerate the role of their home state in appraising U.S. history. *Psychological Science, 29(9)*, 1414-1422. https://doi.org/10.1177/0956797618772504

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797618772504)
- [OSF](https://osf.io/m3w2g)

## Paper 4

Murphy, G., Loftus, E. F., Hofstein Grady, R., Levine, L. J., & Greene, C. M. (2019). False memories for fake news during Ireland's abortion referndum. *Psychological Science, 30(10)*, 1449-1459. https://doi.org/10.1177/0956797619864887

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797619864887)
- [OSF](https://osf.io/9q23j)

## Paper 5

Li, Q., Zhang, W., Heyman, G. D., Compton, B. J., & Lee, K. (2020). Susceptibility to being lured away by a stranger: A real-world field test of selective trust in early childhood. *Psychological Science, 31(12)*, 1488-1496. https://doi.org/10.1177/0956797620966526

- [paper](https://journals.sagepub.com/doi/full/10.1177/0956797620966526)
- [OSF](https://osf.io/arjzw)