---
title: "week 1"
description: |
  The first blog post of my internship. What I set out to do, what I achieved, the challenges I encountered...
author:
  - name: Bonnie Butler
date: 02-18-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# a recap on the first week

We decided that my internship project would involve selecting several open data research papers from the Psychological Science journal and trying to replicate the data using R.

In doing so, I hope to learn exactly how straightforward it is to replicate the data from these open science papers, and to become more comfortable using R, as I really think it’s a fantastic statistical program.

In Week 1, I set out to customise my blog site, select some open data science papers I found interesting, and plan what I hope to achieve each week as part of this internship.

Tasks that I completed this week include:

- Customising my blog site, e.g., changing the theme, updating details on the home page, publishing a test blog post

- Finding & saving the data from 5 research papers with open data - I’ve chosen one for each year from 2016-2020

- Saving links to the research papers & open data on a page linked to my blog site*

*One of my tasks this week is to actually link said page to my blog. I can pull up the page by searching for it in the search bar on my blog, but there is no direct link from my site at the moment.

I did not put together a plan for each week, so that will be a task for this week! As well as starting to look at the 2016 paper and determining the steps required to replicate the data on R.